apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: stock-demo
type: Opaque
stringData:
  username: stock # required field for kubernetes.io/basic-auth
  password: Veeam123! # required field for kubernetes.io/basic-auth