apiVersion: v1
kind: Service
metadata:
  name: external-postgresql 
  namespace: stock-demo #Application's namespace
spec:
  type: ExternalName
  externalName: linuxapps.homelab.local    #FQDN of PostgreSQL instance
