apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: stock-demo
type: Opaque
data:
  username: c3RvY2s= # required field for kubernetes.io/basic-auth
  password: VmVlYW0xMjMh # required field for kubernetes.io/basic-auth
  host: ZXh0ZXJuYWwtcG9zdGdyZXNxbC5zdG9jay1kZW1vLnN2Yy5jbHVzdGVyLmxvY2Fs
  port: NTQzMg==
  db_name: c3RvY2s= #DB to be protected, only required for single database backup 