---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-demo-deploy
  namespace: stock-demo
  labels:
    app: stock-demo
    purpose: production
    dataprotection: k10-gold
    immutable: enabled  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-demo
  template:
    metadata:
      labels:
        app: stock-demo
    spec:
      containers:
        - name: stock-demo
          image: tdewin/stock-demo
          ports:
            - name: stock-demo
              containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: postgresql-configmap
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: postgresql-configmap
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgresql-secret
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: postgresql-configmap
            - name: ADMINKEY
              value: unlock
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgresql-secret
